USE master
GO
DROP DATABASE IF EXISTS DEMO04
GO
CREATE DATABASE DEMO04
GO
USE DEMO04;
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    IDCLI int identity(1,1) NOT NULL,
    NOMCLIE varchar(50)  NOT NULL,
    APECLIE varchar(50)  NOT NULL,
    DOCCLIE char(8)  NOT NULL,
    EMACLIE varchar(50)  NOT NULL,
    CELCLIE char(9)  NOT NULL,
    ESTCLIE char(1)  NOT NULL,
	IDUBI int NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY  (IDCLI)
);


CREATE TABLE UBIGEO (
    IDUBI int identity(1,1) NOT NULL,
    PAISUBI varchar(50)  NOT NULL,
    DEPUBI varchar(50)  NOT NULL,
    PROVUBI char(50)  NOT NULL,
    DISUBI varchar(50)  NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY  (IDUBI)
);

-- foreign keys
-- Reference: COMPRA_DETALLE_COMPRA (table: COMPRA_DETALLE)
ALTER TABLE CLIENTE ADD CONSTRAINT UBIGEO_CLIENTE
    FOREIGN KEY (IDUBI)
    REFERENCES UBIGEO (IDUBI);



insert into UBIGEO
(PAISUBI,DEPUBI,PROVUBI,DISUBI)
values
('PERU','LIMA','CAÑETE','CHILCA'),
('PERU','LIMA','CAÑETE','CHILCA'),
('PERU','LIMA','CAÑETE','CHILCA'),
('PERU','LIMA','CAÑETE','SAN ANTONIO'),
('PERU','LIMA','CAÑETE','SANTA CRUZ DE FLORES'),
('PERU','LIMA','CAÑETE','CALANGO'),
('PERU','LIMA','CAÑETE','MALA'),
('PERU','LIMA','CAÑETE','COAYLLO'),
('PERU','LIMA','CAÑETE','ASIA'),
('PERU','LIMA','CAÑETE','CERRO AZUL'),
('PERU','LIMA','CAÑETE','QUILMANA'),
('PERU','LIMA','CAÑETE','SAN LUIS'),
('PERU','LIMA','CAÑETE','IMPERIAL'),
('PERU','LIMA','CAÑETE','NUEVO IMPERIAL'),
('PERU','LIMA','CAÑETE','SAN VICENTE DE CAÑETE'),
('PERU','LIMA','CAÑETE','LUNAHUANA'),
('PERU','LIMA','CAÑETE','PACARAN'),
('PERU','LIMA','CAÑETE','ZUÑIGA'),
('PERU','ICA','ICA','ICA'),
('PERU','ICA','ICA','OCUCAJE'),
('PERU','ICA','ICA','PACHACUTEC'),
('PERU','ICA','ICA','PARCONA'),
('PERU','ICA','NAZCA','NAZCA'),
('PERU','ICA','NAZCA','EL INGENIO'),
('PERU','ICA','NAZCA','MARCONA'),
('CHILE','TARAPACA','IQUIQUE','IQUI');


insert into CLIENTE
(NOMCLIE,APECLIE,DOCCLIE,EMACLIE,CELCLIE,ESTCLIE, IDUBI)
values
('Miguel','Gutierrez','78452169','miguel@gmail.com','995687412','A', 6),
('Jose','Sivera','14256985','jose@gmail.com','992666961','A', 5),
('Mario','Quispe','74200697','mario@gmail.com','992693446','A', 4);